import ListTable from "@/app/inicio/administrador/nombre-tabla/table/listTable";
import DataRender from "@/components/DataRender";
import { IGetTableNombreTabla, ITableDataNombreTabla } from "@/models/interfaces/nombre-tabla.interfaces";
import { listTableData } from "@/services/table-name.service";


export default async function GetTable({ search }: IGetTableNombreTabla) {
  //const { data } = await listTableData(search);

  const data: ITableDataNombreTabla[] = [
    { id: 1, table: "IPS Cod Habilitacion", code: "123", name: "SANTIAGO MONSALVE", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat1", enabled: true, createdAt: "2024-02-13T10:00:00Z", updatedAt: "2024-02-13T12:00:00Z", category: "Salud", type: "Hospital", city: "Medellín", country: "Colombia", email: "santiago.monsalve@example.com", phone: "+57 123 456 7890", tag1: "Atención primaria", tag2: "Urgencias" },
    { id: 2, table: "IPS Cod Habilitacion", code: "456", name: "JUAN PÉREZ", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat2", enabled: false, createdAt: "2024-02-12T08:30:00Z", updatedAt: "2024-02-13T09:45:00Z", category: "Salud", type: "Clínica", city: "Bogotá", country: "Colombia", email: "juan.perez@example.com", phone: "+57 987 654 3210", tag1: "Consulta externa", tag2: "Especialidades" },
    { id: 3, table: "IPS Cod Habilitacion", code: "789", name: "MARÍA GÓMEZ", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat3", enabled: true, createdAt: "2024-02-11T14:20:00Z", updatedAt: "2024-02-12T16:30:00Z", category: "Salud", type: "Centro de salud", city: "Cali", country: "Colombia", email: "maria.gomez@example.com", phone: "+57 321 654 9870", tag1: "Pediatría", tag2: "Consulta externa" },
    { id: 4, table: "IPS Cod Habilitacion", code: "101", name: "LUIS FERNÁNDEZ", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat4", enabled: false, createdAt: "2024-02-10T09:45:00Z", updatedAt: "2024-02-11T11:10:00Z", category: "Salud", type: "Consultorio", city: "Cartagena", country: "Colombia", email: "luis.fernandez@example.com", phone: "+57 876 543 2109", tag1: "Medicina general", tag2: "Chequeos" },
    { id: 5, table: "IPS Cod Habilitacion", code: "202", name: "CARLOS RAMÍREZ", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat5", enabled: true, createdAt: "2024-02-09T15:10:00Z", updatedAt: "2024-02-10T18:25:00Z", category: "Salud", type: "Hospital", city: "Barranquilla", country: "Colombia", email: "carlos.ramirez@example.com", phone: "+57 654 321 0987", tag1: "Cirugía", tag2: "Hospitalización" },
    { id: 6, table: "IPS Cod Habilitacion", code: "202", name: "CARLOS RAMÍREZ", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat5", enabled: true, createdAt: "2024-02-09T15:10:00Z", updatedAt: "2024-02-10T18:25:00Z", category: "Salud", type: "Hospital", city: "Barranquilla", country: "Colombia", email: "carlos.ramirez@example.com", phone: "+57 654 321 0987", tag1: "Cirugía", tag2: "Hospitalización" },
    { id: 7, table: "IPS Cod Habilitacion", code: "202", name: "CARLOS RAMÍREZ", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat5", enabled: true, createdAt: "2024-02-09T15:10:00Z", updatedAt: "2024-02-10T18:25:00Z", category: "Salud", type: "Hospital", city: "Barranquilla", country: "Colombia", email: "carlos.ramirez@example.com", phone: "+57 654 321 0987", tag1: "Cirugía", tag2: "Hospitalización" },
    { id: 8, table: "IPS Cod Habilitacion", code: "202", name: "CARLOS RAMÍREZ", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat5", enabled: true, createdAt: "2024-02-09T15:10:00Z", updatedAt: "2024-02-10T18:25:00Z", category: "Salud", type: "Hospital", city: "Barranquilla", country: "Colombia", email: "carlos.ramirez@example.com", phone: "+57 654 321 0987", tag1: "Cirugía", tag2: "Hospitalización" },
    { id: 9, table: "IPS Cod Habilitacion", code: "202", name: "CARLOS RAMÍREZ", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat5", enabled: true, createdAt: "2024-02-09T15:10:00Z", updatedAt: "2024-02-10T18:25:00Z", category: "Salud", type: "Hospital", city: "Barranquilla", country: "Colombia", email: "carlos.ramirez@example.com", phone: "+57 654 321 0987", tag1: "Cirugía", tag2: "Hospitalización" },
    { id: 10, table: "IPS Cod Habilitacion", code: "202", name: "CARLOS RAMÍREZ", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat5", enabled: true, createdAt: "2024-02-09T15:10:00Z", updatedAt: "2024-02-10T18:25:00Z", category: "Salud", type: "Hospital", city: "Barranquilla", country: "Colombia", email: "carlos.ramirez@example.com", phone: "+57 654 321 0987", tag1: "Cirugía", tag2: "Hospitalización" },
    { id: 11, table: "IPS Cod Habilitacion", code: "202", name: "CARLOS RAMÍREZ", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat5", enabled: true, createdAt: "2024-02-09T15:10:00Z", updatedAt: "2024-02-10T18:25:00Z", category: "Salud", type: "Hospital", city: "Barranquilla", country: "Colombia", email: "carlos.ramirez@example.com", phone: "+57 654 321 0987", tag1: "Cirugía", tag2: "Hospitalización" },
    { id: 12, table: "IPS Cod Habilitacion", code: "202", name: "CARLOS RAMÍREZ", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat5", enabled: true, createdAt: "2024-02-09T15:10:00Z", updatedAt: "2024-02-10T18:25:00Z", category: "Salud", type: "Hospital", city: "Barranquilla", country: "Colombia", email: "carlos.ramirez@example.com", phone: "+57 654 321 0987", tag1: "Cirugía", tag2: "Hospitalización" },
    { id: 13, table: "IPS Cod Habilitacion", code: "202", name: "CARLOS RAMÍREZ", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat5", enabled: true, createdAt: "2024-02-09T15:10:00Z", updatedAt: "2024-02-10T18:25:00Z", category: "Salud", type: "Hospital", city: "Barranquilla", country: "Colombia", email: "carlos.ramirez@example.com", phone: "+57 654 321 0987", tag1: "Cirugía", tag2: "Hospitalización" },
    { id: 14, table: "IPS Cod Habilitacion", code: "202", name: "CARLOS RAMÍREZ", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat5", enabled: true, createdAt: "2024-02-09T15:10:00Z", updatedAt: "2024-02-10T18:25:00Z", category: "Salud", type: "Hospital", city: "Barranquilla", country: "Colombia", email: "carlos.ramirez@example.com", phone: "+57 654 321 0987", tag1: "Cirugía", tag2: "Hospitalización" },
    { id: 15, table: "IPS Cod Habilitacion", code: "202", name: "CARLOS RAMÍREZ", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat5", enabled: true, createdAt: "2024-02-09T15:10:00Z", updatedAt: "2024-02-10T18:25:00Z", category: "Salud", type: "Hospital", city: "Barranquilla", country: "Colombia", email: "carlos.ramirez@example.com", phone: "+57 654 321 0987", tag1: "Cirugía", tag2: "Hospitalización" },
    { id: 16, table: "IPS Cod Habilitacion", code: "202", name: "CARLOS RAMÍREZ", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat5", enabled: true, createdAt: "2024-02-09T15:10:00Z", updatedAt: "2024-02-10T18:25:00Z", category: "Salud", type: "Hospital", city: "Barranquilla", country: "Colombia", email: "carlos.ramirez@example.com", phone: "+57 654 321 0987", tag1: "Cirugía", tag2: "Hospitalización" },
    { id: 17, table: "IPS Cod Habilitacion", code: "202", name: "CARLOS RAMÍREZ", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat5", enabled: true, createdAt: "2024-02-09T15:10:00Z", updatedAt: "2024-02-10T18:25:00Z", category: "Salud", type: "Hospital", city: "Barranquilla", country: "Colombia", email: "carlos.ramirez@example.com", phone: "+57 654 321 0987", tag1: "Cirugía", tag2: "Hospitalización" },
    { id: 18, table: "IPS Cod Habilitacion", code: "202", name: "CARLOS RAMÍREZ", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat5", enabled: true, createdAt: "2024-02-09T15:10:00Z", updatedAt: "2024-02-10T18:25:00Z", category: "Salud", type: "Hospital", city: "Barranquilla", country: "Colombia", email: "carlos.ramirez@example.com", phone: "+57 654 321 0987", tag1: "Cirugía", tag2: "Hospitalización" },
    { id: 19, table: "IPS Cod Habilitacion", code: "202", name: "CARLOS RAMÍREZ", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat5", enabled: true, createdAt: "2024-02-09T15:10:00Z", updatedAt: "2024-02-10T18:25:00Z", category: "Salud", type: "Hospital", city: "Barranquilla", country: "Colombia", email: "carlos.ramirez@example.com", phone: "+57 654 321 0987", tag1: "Cirugía", tag2: "Hospitalización" },
    { id: 20, table: "IPS Cod Habilitacion", code: "202", name: "CARLOS RAMÍREZ", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat5", enabled: true, createdAt: "2024-02-09T15:10:00Z", updatedAt: "2024-02-10T18:25:00Z", category: "Salud", type: "Hospital", city: "Barranquilla", country: "Colombia", email: "carlos.ramirez@example.com", phone: "+57 654 321 0987", tag1: "Cirugía", tag2: "Hospitalización" },
    { id: 21, table: "IPS Cod Habilitacion", code: "202", name: "CARLOS RAMÍREZ", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat5", enabled: true, createdAt: "2024-02-09T15:10:00Z", updatedAt: "2024-02-10T18:25:00Z", category: "Salud", type: "Hospital", city: "Barranquilla", country: "Colombia", email: "carlos.ramirez@example.com", phone: "+57 654 321 0987", tag1: "Cirugía", tag2: "Hospitalización" },
    { id: 22, table: "IPS Cod Habilitacion", code: "202", name: "CARLOS RAMÍREZ", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat5", enabled: true, createdAt: "2024-02-09T15:10:00Z", updatedAt: "2024-02-10T18:25:00Z", category: "Salud", type: "Hospital", city: "Barranquilla", country: "Colombia", email: "carlos.ramirez@example.com", phone: "+57 654 321 0987", tag1: "Cirugía", tag2: "Hospitalización" },
    { id: 23, table: "IPS Cod Habilitacion", code: "202", name: "CARLOS RAMÍREZ", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat5", enabled: true, createdAt: "2024-02-09T15:10:00Z", updatedAt: "2024-02-10T18:25:00Z", category: "Salud", type: "Hospital", city: "Barranquilla", country: "Colombia", email: "carlos.ramirez@example.com", phone: "+57 654 321 0987", tag1: "Cirugía", tag2: "Hospitalización" },
    { id: 24, table: "IPS Cod Habilitacion", code: "202", name: "CARLOS RAMÍREZ", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat5", enabled: true, createdAt: "2024-02-09T15:10:00Z", updatedAt: "2024-02-10T18:25:00Z", category: "Salud", type: "Hospital", city: "Barranquilla", country: "Colombia", email: "carlos.ramirez@example.com", phone: "+57 654 321 0987", tag1: "Cirugía", tag2: "Hospitalización" },
    { id: 25, table: "IPS Cod Habilitacion", code: "202", name: "CARLOS RAMÍREZ", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat5", enabled: true, createdAt: "2024-02-09T15:10:00Z", updatedAt: "2024-02-10T18:25:00Z", category: "Salud", type: "Hospital", city: "Barranquilla", country: "Colombia", email: "carlos.ramirez@example.com", phone: "+57 654 321 0987", tag1: "Cirugía", tag2: "Hospitalización" },
    { id: 26, table: "IPS Cod Habilitacion", code: "202", name: "CARLOS RAMÍREZ", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat5", enabled: true, createdAt: "2024-02-09T15:10:00Z", updatedAt: "2024-02-10T18:25:00Z", category: "Salud", type: "Hospital", city: "Barranquilla", country: "Colombia", email: "carlos.ramirez@example.com", phone: "+57 654 321 0987", tag1: "Cirugía", tag2: "Hospitalización" },
  ];

  return (
    <>
    <DataRender
      data={data}
      RenderComponent={<ListTable tableData={data} />}
      EmptyComponent={<p className='text-center'>No hay datos</p>}
    />
    </>
  );
}
