//#region ⚠️ estilos globales de Next JS - NO modificar esta sección 🚨
import '../styles/global/tailwind/index-tailwind.css';
import '../styles/global/scss/main.scss';
//#endregion

import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { PrimeReactProvider } from 'primereact/api';
import { Toaster } from 'react-hot-toast';
import { Suspense } from 'react';
import FixedLoader from '@/shared/ui/FixedLoader';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='es-ES'>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <FixedLoader />

        <Toaster position='top-right' reverseOrder={true} />

        <div className='mx-auto max-w-[1920px]'>
          <PrimeReactProvider>{children}</PrimeReactProvider>
        </div>
      </body>
    </html>
  );
}
