import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { PrimeReactProvider } from 'primereact/api';
import { Toaster } from 'react-hot-toast';
import '../styles/index.scss';
import LoaderInApiRequest from '@/components/loading/spinner/LoaderInApiRequest';
import { Suspense } from 'react';
import NavigationLoader from '@/components/loading/spinner/navigation-spinner/NavigationLoader';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <LoaderInApiRequest />
        <Suspense fallback={null}>
          <NavigationLoader />
        </Suspense>

        <Toaster position='top-right' reverseOrder={true} />

        <PrimeReactProvider>{children}</PrimeReactProvider>
      </body>
    </html>
  );
}
